# Generated by Django 2.0 on 2017-12-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('searched_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
