# Generated by Django 2.0 on 2017-12-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ('-searched_date',)},
        ),
    ]
